version: "3"

services:
  server:
    build:
      context: .
    container_name: teme_server
    env_file:
      - ./.env
    networks:
      - teme_net
    depends_on:
      - redis
    ports:
      - 4000:3000
